name: CI
on:
  - push
  - workflow_dispatch
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: danysk/action-checkout@0.2.13
      - uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'sbt'
      - name: Run tests
        run: sbt -v +test
      - name: Run Cucumber
        run: sbt cucumber
    