name: CI
on:
  - push
  - workflow_dispatch
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: danysk/action-checkout@0.2.13
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: openjdk@1.17
      - name: View sbt folders
        run: ls ~/.sbt
      - name: Run tests
        run: sbt -v +test
      - name: Run Cucumber
        run: sbt cucumber
    