name: CI
on:
  - push
  - workflow_dispatch
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: danysk/action-checkout@0.2.13
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: openjdk@1.17
      - name: Show library resolvers
        run: sbt "show resolvers"
      - name: View plugin dependencies
        run: sbt "reload plugins" "dependencyTree"
      - name: Run compile
        run: sbt compile
      - name: View sbt folders
        run: tree ~/.sbt
      - name: Run test
        run: sbt -v +test
    