name: CI
on:
  - push
  - workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: danysk/action-checkout@0.2.13
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: openjdk@1.17
      - name: Generate Scaladoc
        run: sbt doc
      - name: Generate Documentation website
        run: | 
            cd docs
            npm run build
            mv ../api/ ./build/
      - name: Check project structure
        run: ls
